### ISSUE TITLE
Feature request - options extension control 

### ISSUE THREAD

**Issue by bginsburg** [ovhemert/gatsby-plugin-zopfli#16]
Hi team,

We are using this plugin with amazon s3,
One of the requirements of accessing a "gz" file is to name the file without the extension.
ie. /public/lobby.html.gz -> /public/lobby.html (and that will be the gzip file)
Then i add the metadata specifying this file is gzip encoded so the consumer can read it.

At the moment i had to manually change it and using an unsupported version,
I would love to have an extension control as one of the options
ie.
```
options: {
   fileExtention: '', //default can be gz
}
``` 

Is that something we can add?
I don't mind creating the PR for it

**Comment by ovhemert** [comment]
You're welcome to create a PR for this. It would be a nice addition. 👍🏻

Please note that there is also an option to specify the output path. If we create output files with the same extension (`fileExtention: ''`) as the input files, `path` needs to be specified to prevent collision. And please default the extension to `gz` so we'll stay backwards compatible.

**Comment by bginsburg** [comment]
For my use case having it override the exiting files is the what i'm looking for,
I can edit the readme specifying that `fileExtention:''` without `path` will lead to overwriting existing files. 
Since this plugin is used mainly in production builds i can't see why keeping the un-zipped version will be required (i think all browsers read gzip from 2003)

**Comment by bginsburg** [comment]
Also i'm having permission issues pushing my PR not sure why :/

**Comment by ovhemert** [comment]
no problem to overwrite the files if this is clear from the docs
