### ISSUE TITLE
cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by artemartemov** [ovhemert/gatsby-plugin-zopfli#22]
## 🐛 Bug Report

version: `"gatsby-plugin-zopfli": "^2.0.0",`

running into build issue on netfliy:
```
success open and validate gatsby-configs - 0.073s
11:09:02 AM: error Error in "/opt/build/repo/web/node_modules/gatsby-plugin-zopfli/gatsby-node.js": Cannot find module 'worker_threads'
11:09:02 AM: 
11:09:02 AM: 
11:09:02 AM:   Error: Cannot find module 'worker_threads'
```

## To Reproduce

- install zopfli gatsby plugin
- deploy to netlify

Paste your code here:

```js
{
      resolve: "gatsby-plugin-zopfli",
      options: {
        extensions: ["css", "html", "js", "svg"]
      }
    }
```

**Comment by ovhemert** [comment]
This new version (2.x) is only compatible with Node.js v12.x or higher. Please make sure your building on a compatible version.
